### ISSUE TITLE
Host Manager skipped the host unlock step

### ISSUE THREAD

**Issue by sia-steve** [siacentral/host-manager#1]
Absolutely loving Host Manager so far!

When I chose to import my Sia settings (I checked the Advanced settings box), I was directed to enter my wallet unlock password. This was also the page that mentioned I could set the system environment variable. I chose to let Host Manager unlock my wallet for me and entered my wallet password. Success on this step.

The next screen popped up, and appeared to have some additional info regarding unlocking the wallet for hosting. I think it wanted me to enter my password again. I didn't read too much on this screen because it automatically skipped through this into the "Scanning" screen, and then finally into the app.

**Comment by n8maninger** [comment]
@sia-steve did you actually see the advanced settings screen or did it skip over it entirely after unlocking the wallet? The advanced settings has textboxes for API Address, API User Agent, Host Port and RPC Port.

**Comment by n8maninger** [comment]
I added a separate issue for the advanced settings screen not displaying after importing settings from Sia-UI #2

**Comment by n8maninger** [comment]
Fixed by d2ce4fe

There were two different places that attempted to unlock the wallet. I ended up removing the one in setup to reduce complexity and code duplication. The remaining one will now be shown directly after setup before you are able to get into the main app or if your wallet is locked.
