### ISSUE TITLE
Automatic Updates

### ISSUE THREAD

**Issue by n8maninger** [siacentral/host-manager#12]
Automatic updates are technically already enabled, but I'd like to customize how they work more. Updates are checked currently only when Host Manager is first run and never again. I'd like to change that to check every few hours. In addition, I'd like to add a custom display on the UI for when an update is ready for install.

**Comment by MeijeSibbel** [comment]
I think having something like the discord update button in the top right corner would be a good start. When you click it, the app closes and installs the new version.
One thing that i would like to point out is that i'm quite uncertain when to update. I would like the app to find a point in time where there is no more data being transferred and update then.

**Comment by n8maninger** [comment]
Unfortunately, there's no way for me to hook into the process of whether someone is uploading files or not at the moment. I could add port scanning for any data being received on 9982, but that could be cpu intensive for slower apps and would likely require a separate install. That'd be a nice addition to Sia though.

**Comment by n8maninger** [comment]
An update now button has been added to the bottom left corner of the UI when an update is available.

6abb0d2
