### ISSUE TITLE
Ability to change API key

### ISSUE THREAD

**Issue by PNRxA** [siacentral/host-manager#18]
Currently if the API key changes (e.g after an upgrade with a docker container) the application won't prompt to change API key but stay on "API credentials invalid".

I believe there should be an option in the UI to change the API key instead of having to go into the config file to update it manually. Is there a way to do this that I missed?

**Comment by n8maninger** [comment]
There is not currently a way to fix this without manually updating the config, that's an excellent addition. I will get this added.

**Comment by n8maninger** [comment]
Fixed by 669b7bd

**Comment by n8maninger** [comment]
As a follow-up to this: if you are using docker the next time you update your container you should add `-e SIA_API_PASSWORD=yourpasswordhere` to force the password to stay the same between container restarts.

**Comment by PNRxA** [comment]
@n8maninger Appreciate the quality of life update and the advice :)
