### ISSUE TITLE
[Bug] MacOS Application still running after exit

### ISSUE THREAD

**Issue by alen-z** [siacentral/host-manager#19]
Sia Host Manager still seen in Activity Monitor after exit. I like the product.

**Comment by n8maninger** [comment]
Host Manager goes to the tray, regardless of `CMD+Q` this is intentional as Hosts should not be shutting themselves down accidentally.

If you want to exit Sia Host Manger completely click the tray icon and select "Exit"

**Comment by alen-z** [comment]
Ow, there is no visible icon then.

<img width="243" alt="image" src="https://user-images.githubusercontent.com/7421289/76669518-3f4c1900-658c-11ea-88e1-0e41e9b84623.png">

If I click in place where it should be, it works.

<img width="147" alt="image" src="https://user-images.githubusercontent.com/7421289/76669547-69054000-658c-11ea-9636-c244abbc227c.png">
