### ISSUE TITLE
[bug] Host port must match the format

### ISSUE THREAD

**Issue by alen-z** [siacentral/host-manager#20]
While trying to change currency, I notices `Update` button is not available because of apparent host:port formatting. Field does not accept `sbox.myds.me:9982`.

**Comment by alen-z** [comment]
https://github.com/siacentral/host-manager/blob/ba822e8e6dc99ba3c0f0a94bf2e4116f0849a9c9/src/components/SettingsModal.vue#L139

I guess this should be addressed.

**Comment by n8maninger** [comment]
Your host port should not include the domain. The settings page is for Daemon settings, not host settings like netaddress.

If you want to change your host's netaddress use the announce button from the configuration page and change the dropdown to "Custom"

**Comment by alen-z** [comment]
I would like to suggest at least removing `:` then.
