### ISSUE TITLE
Not running on Raspberry Pi ARM

### ISSUE THREAD

**Issue by BouweCeunen** [siacentral/host-manager#23]
Is this possible to run on ARM cpu on Raspberry Pi? I tried the .deb and also tried to run it with npm but no luck, hitting a lot of walls. Any help?

Standard dpkg deb install gave me a lot of broken packages. Trying with gdebi gives me this, but I'm not able to install further.

![image](https://user-images.githubusercontent.com/5576686/78999903-e2705e00-7b4b-11ea-8e4f-99a18c0777a5.png)

**Comment by n8maninger** [comment]
I'm currently testing releases for arm64 devices. I am also getting that issue, but I have not found a great solution yet.. Unfortunately Electron does not have great resources for ARM based devices.

This hasn't been very high on my to-do list as the next version of Host Manager will come embedded with a web based portal. The electron app will be optional.

**Comment by BouweCeunen** [comment]
Alright great, that will be even better!

**Comment by christophediprima** [comment]
That's a great news! Any idea on when this is planed to be released?
