### ISSUE TITLE
timeout when trying to connect to 192.168.225.100:9982.

### ISSUE THREAD

**Issue by Synthacon** [siacentral/host-manager#28]
Hi,
How to fix this?

timeout when trying to connect to 192.168.225.100:9982.
Results (2/5 Tests Passed)
Net address resolved
Net Address
192.168.225.100:9982
Resolved IP
192.168.225.100
Last Announcement
192.168.225.100:9982 (Apr 24, 2018)
Cannot connect to host
test skipped: unable to connect
test skipped: unable to retrieve host settings
SiaMux Port
Elapsed Time
0ms

**Comment by n8maninger** [comment]
192.168.225.100 looks like a private IP address, you need to announce your host using your public IP address. You can get this from https://ipchicken.com

You will also probably need to forward ports 9982 and 9983 on your router to your host

**Comment by n8maninger** [comment]
Closing as this is not an issue with Host Manager
