### ISSUE TITLE
Currency automatically reverts to USD

### ISSUE THREAD

**Issue by jwaes** [siacentral/host-manager#39]
App Version: v1.0.30
Sia Daemon Version: v1.5.4

I go to Settings, App Settings, put currency to EUR and click update.
Then i go to Configuration, change some rates. click update configuation, click announce.

Then currency is back to USD. The Configuration screen is showing a mismatch of both USD and the euro currency symbol. And on the App Settings screen there is again mentioned USD.

**Comment by n8maninger** [comment]
Thanks for the bug report, I was able to track down the issue and get it fixed. I'll get a new version tested and released before the weekend.
