### ISSUE TITLE
Allow connecting to a remote siad

### ISSUE THREAD

**Issue by ianlevesque** [siacentral/host-manager#5]
I run siad on another machine but I'd still like to be able to use host manager.

**Comment by n8maninger** [comment]
Thanks for this! I'm experimenting with different options right now. Unfortunately Sia only allows API connections on the machine Sia is running on. So it can't just be plug-and-play. At the very least it would require installing something on the target machine.

I think this is going to have to stay in the realm of Sia Central web, the online remote e2e encrypted Sia Host Manager. Eventually the web and desktop versions will have feature parity.

**Comment by tbenz9** [comment]
The default behavior is to only allow API connections on the machine Sia is running, but that can be changed with CLI flags.  I've been meaning to look into what it would take to have Sia accept API connections from a subnet or list of IPs, instead of a single IP.

**Comment by n8maninger** [comment]
In that vein. It would be nice to be able to restrict certain IP or subnets to certain modules. Only allow `/wallet/siacoins` to be accessed by `localhost` but `/host` to be accessed by `192.168.1.0/24` for instance.

**Comment by tbenz9** [comment]
I've opened a Sia feature request for this request: https://gitlab.com/NebulousLabs/Sia/issues/3655

@DavidVorick

**Comment by sudoc** [comment]
Can we just use SSH port forwarding for now? I think it is really secure way to access remote ports.

**Comment by n8maninger** [comment]
Yes, using SSH port forwarding works just fine. I use it for my primary host. However, you will not be able to add new storage folders.

**Comment by Eucliwood090** [comment]
Hello, Like you, I use ssh to connect with Sia Host Manager, it would be possible to make several connection profiles on Sia Host Manager.

I am using tunnel on 127.0.0.1, 127.0.0.2, 127.0.0.3 with putty

But I have to restart Sia Host Manager every time

**Comment by systemmonkey42** [comment]
Can you build this as a web app?  It would be easier to manage my remote host if I could just browse to it (its on another site, via a VPN).

I'm more than happy to drop a web server on the machine, or even run this in a container with access to the Sia host data directory.
