### ISSUE TITLE
IPv6 adresses confuse hosts with a Port attached [2a02:8071:82a2:1e00:74d9:5f9:57f6:822a]:9982

### ISSUE THREAD

**Issue by Bubbu17** [siacentral/host-manager#50]
Hello , i tried to get mi sia Host running with an IPv6 Adress but i get this massage iv i check the function over  https://troubleshoot.siacentral.com/sia/%5B2a02:8071:82a2:1e00:74d9:5f9:57f6:822a%5D:9982?unit=decimal&currency=eur

![image](https://user-images.githubusercontent.com/62136070/116919847-2e5bdc80-ac52-11eb-8967-06e331894135.png)

but basically the host is running
![image](https://user-images.githubusercontent.com/62136070/116920107-8c88bf80-ac52-11eb-9d59-30affc2286c4.png)

could you please check and give a hint on how to solve it soon.

Thanks in advance Torsten

**Comment by n8maninger** [comment]
I fixed the issue on my end and reset your uptime. Your host looks healthy. It currently has a `read/write on closed pipe` for the RHP3 benchmark, but it should fix itself eventually.
