### ISSUE TITLE
couldn't be accessed by user '_apt'

### ISSUE THREAD

**Issue by BHare1985** [siacentral/host-manager#53]
Full log: https://pixeldrain.com/u/M9RKJ5Da

```
#apt install -f ~/Sia.Host.Manager-v1.0.34.deb
... ( few minutes later) ...
Processing triggers for libgdk-pixbuf2.0-0:amd64 (2.38.1+dfsg-1) ...
N: Download is performed unsandboxed as root as file '/root/Sia.Host.Manager-v1.0.34.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
```

I am logged in as root, is that the issue?

Debian GNU/Linux 10 (buster
4.19.0-16-amd64

**Comment by n8maninger** [comment]
Host Manager is a graphical desktop app, on most distro's you can just double click the deb to install. 

This is most likely due to the `_apt` user not having read or write access to the downloaded `Sia.Host.Manager-v1.0.34.deb`. Fixing the permissions should get rid of the error.

**Comment by rfh237** [comment]
change the permissions
