### ISSUE TITLE
correct settings for handyhost

### ISSUE THREAD

**Issue by bigmac5753** [siacentral/host-manager#68]
I've installed sia via handyhost and want to run host-manager but not sure of the correct settings to connect to handyhost

**Comment by timrettop** [comment]
@bigmac5753 I use the following SSH tunnels to my headless system running HH: 

ssh -L 9980:localhost:9980 -L 10801:localhost:10801 

And in Sia Host Mgr I use localhost:10801 for API address, and I retrieved the API Password from /root/.sia/apipassword

**Comment by n8maninger** [comment]
Since this is not an issue with Host Manager, I'm closing. Please use the official Sia Discord for further support.
