### ISSUE TITLE
Read and Write Failure Rate

### ISSUE THREAD

**Issue by mauroinagoki** [siacentral/host-manager#74]
Can anyone tell me why the H: partition is giving read and write errors? 
While other partition F: is ok.

Capacity of H: occupies half on disk 0 and other half is used for backup of personal files.
And F: occupies the other entire disk.

![image](https://user-images.githubusercontent.com/379786/155899532-4c9afa2e-1ba9-410f-9775-32e8d8dc7f13.png)

**Comment by n8maninger** [comment]
That means there's an intermittent error writing and reading from that disk. Check your connections and make sure the disk is not failing. Since this is not an issue with Host Manager, I'm closing. Please use the official Sia Discord for further support.
