### ISSUE TITLE
Sia Host Manager + Ubuntu LTS file directory problem

### ISSUE THREAD

**Issue by j03020** [siacentral/host-manager#82]
After upgrading to the new Ubuntu LTS version I have encountered several problems with sia host manager.
First the appimage version did not want to start, discovered I had to install libfuse for appimages to work again. Now sia host manager is starting without a hitch. Next problem I have encountered is that sia host manager complains about having no access to the file directories? ("path/xyz/ is inaccessible. This can cause data corruption and revenue loss. Check your folder path and permissions") I'm still finishing contracts and did not change any permissions. Anyone got a tip for me on how to solve this issue?

**Comment by n8maninger** [comment]
I updated Electron to support Ubuntu 22.04.

As far as the inaccessible folder goes, that's usually a permissions/connection issue from `siad` and unrelated to Host Manager.
