### ISSUE TITLE
web version

### ISSUE THREAD

**Issue by dnnspaul** [siacentral/host-manager#88]
Having a web version would be a massive improvement instead of using the desktop app. Since it's built with electron, it should already have a solid foundation to work from.

IMO having the storj web interface is an advantage in contrast to use a desktop app, especially because I have to open several port tunnels to my node for using the desktop app.

Is it planned to release a (maybe docker-based) web version of the host manager? Thanks in advance!

**Comment by n8maninger** [comment]
Yes, Host Manager will be deprecated soon in favor of the browser-based `hostd`.
